version: "3.8"

services:
  app:
    env_file:
      - ./.env
    image: traefik:v2.9
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/rules:/rules
      - ./traefik/acme:/acme
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/users:/etc/traefik/users
      - ./traefik/certs:/etc/certs:ro
networks:
  default:
    external:
      name: traefik_proxy
