################################################################
#
# Configuration sample for Traefik v2.
#
# master
# For Traefik v2: https://github.com/traefik/traefik/blob/master/traefik.sample.yml
# sample
# For Traefik v1: https://github.com/traefik/traefik/blob/v1.7/traefik.sample.toml
#
################################################################

################################################################
# Global configuration
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# Traefik logs configuration
################################################################

log:
  level: DEBUG

################################################################
# Access logs configuration
################################################################

accessLog:
  filePath: /traefik.log
  bufferingSize: 100
  filters:
    statusCodes: ["400-499"]

################################################################
# API and dashboard configuration
################################################################

api:
  insecure: true

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  http:
    address: :80
    # Redirect
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: :443
  spice:
    address: :3128

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    # Property exposedbydefault is not allowed.yaml-schema: Traefik v2
    # exposedbydefault: false
    network: traefik_proxy
  file:
    directory: /rules
    watch: true

################################################################
# 인증서
# example: https://doc.traefik.io/traefik/https/acme/
################################################################

certificatesResolvers:
  leresolver:
    acme:
      email: certificate@hyeon.pro
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: http
