################################################################
# DSM
# custom url: https://nas.hyeon.pro/
################################################################
http:
  routers:
    syno_2018__ds218p:
      entryPoints:
        - https
      service: syno_2018__ds218p
      rule: Host(`218p.nas.hyeon.pro`)
      tls:
        certResolver: leresolver
    syno_2018__ds720p:
      entryPoints:
        - https
      service: syno_2018__ds720p
      rule: Host(`720p.nas.hyeon.pro`)
      tls:
        certResolver: leresolver

  services:
    syno_2018__ds218p:
      loadBalancer:
        servers:
          - url: http://192.168.1.159:5000
        passHostHeader: true
    syno_2018__ds720p:
      loadBalancer:
        servers:
          - url: http://192.168.1.55:5000
        passHostHeader: true
